version: '3'

services:
  mysql-standalone :
    image: mysql:latest
    container_name: mysql-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=''
      - MYSQL_DATABASE=projetPH_DB
      - MYSQL_USER=''
      - MYSQL_PASSWORD=''
  springboot-docker-container :
    image: springboot-docker-container
    container_name: spingboot-docker-container
    ports:
      - 8081:8081
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone
      - spring-boot:latest
